### PR TITLE
Add tracer sanitizer

### PR DESCRIPTION
**Pull request by climbfuji**
This PR adds the new tracer_sanitizer scheme to the CCPP prebuild config and two suite definition files (commented out in one of them).

The PR also updates fv3atm with the latest changes from EMC's develop branch (RRTMGP update).

Associated PRs:
https://github.com/NOAA-GSD/ccpp-physics/pull/49
https://github.com/NOAA-GSD/fv3atm/pull/44
https://github.com/NOAA-GSD/ufs-weather-model/pull/36

For regression testing, see https://github.com/NOAA-GSD/ufs-weather-model/pull/36.

### CODE REVIEW

**Comment by climbfuji** [comment]
@joeolson42 @tanyasmirnova @shansun6 @hannahcbarnes please have a look at the suggested call of the tracer_sanitizer scheme in the two modified suite definition files and let me know if this is what you want or what changes you would like me to make. We cannot call it before the `GFS_suite_update` scheme, though. Note that clipping the tracers does not change the diagnostic tendencies. Thanks!

**Comment by tanyasmirnova** [comment]
Dom, I like the name of the subroutine, and the code looks good to me. However, while we avoid getting negative hydrometeors, the mass is not conserved. Could we adopt similar mass conservation procedure as in neg_adj subroutine in the GFDL microphysics?

**Comment by climbfuji** [comment]
> Dom, I like the name of the subroutine, and the code looks good to me. However, while we avoid getting negative hydrometeors, the mass is not conserved. Could we adopt similar mass conservation procedure as in neg_adj subroutine in the GFDL microphysics?

This question came up last week in the global modeling meeting. Georg wanted to try the simple clipping first and then look at the more complicated versions. Everyone, please correct me if I misunderstood the conversation last week.

**Comment by tanyasmirnova** [comment]
I was on vacation and missed this conversation. I agree with Georg to start with the simplest version.

**Comment by hannahcbarnes** [comment]
@climbfuji This seems to fit what we were looking for. 

One question. I see that you have it called once at the very end of the suite definition file. Could we also run into an issue if one of the parameterizations creates negative tendencies. Then, those negative tendencies could be fed into a different parameterization before the next time step? Does this script need to be called after each parameterization?

**Comment by climbfuji** [comment]
> @climbfuji This seems to fit what we were looking for.
> 
> One question. I see that you have it called once at the very end of the suite definition file. Could we also run into an issue if one of the parameterizations creates negative tendencies. Then, those negative tendencies could be fed into a different parameterization before the next time step? Does this script need to be called after each parameterization?

Thanks, @hannahcbarnes. I was wondering the same and hence my question in the fv3atm PR. I guess that is something to play with and decide upon later. For now I leave it at this place so that you developers know how to call it. You can move it around freely until it satisfies your needs.

Ok, I'll pull in some other open PRs before running the tests and opening them up for review.

**Review by DomHeinzeller — APPROVED** [review]

**Pull request merged**
