### PR TITLE
 fix bugs found in pbl and ozone 3d diagnostic tendencies

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
PBL tendencies were missing in two schemes; now fixed.

ccpp PR: https://github.com/NOAA-GSD/ccpp-physics/pull/27/

ufs-weather-model PR: https://github.com/NOAA-GSD/ufs-weather-model/pull/20

### CODE REVIEW

**Comment by climbfuji** [comment]
I see a ton of messages like
```
 69:  NO FLAG: dcnv is generic
119:  FLAG: gwd_opt==1 so gwd not generic
119:  FLAG: satmedmf and isatedmf=1 so pbl not generic
119:  NO FLAG: scnv is generic
119:  NO FLAG: dcnv is generic
 94:  FLAG: gwd_opt==1 so gwd not generic
 94:  FLAG: satmedmf and isatedmf=1 so pbl not generic
 94:  NO FLAG: scnv is generic
 94:  NO FLAG: dcnv is generic
 11:  FLAG: gwd_opt==1 so gwd not generic
 11:  FLAG: satmedmf and isatedmf=1 so pbl not generic
 11:  NO FLAG: scnv is generic
 11:  NO FLAG: dcnv is generic
 73:  FLAG: gwd_opt==1 so gwd not generic
 73:  FLAG: satmedmf and isatedmf=1 so pbl not generic
 73:  NO FLAG: scnv is generic
 73:  NO FLAG: dcnv is generic
120:  FLAG: gwd_opt==1 so gwd not generic
120:  FLAG: satmedmf and isatedmf=1 so pbl not generic
120:  NO FLAG: scnv is generic
120:  NO FLAG: dcnv is generic
 99:  FLAG: gwd_opt==1 so gwd not generic
 99:  FLAG: satmedmf and isatedmf=1 so pbl not generic
```
in the output. We should only print those for the master task in `GFS_typedefs.F90`. Somehow this slipped through the review when the original tendencies code was merged a few weeks back.

**Comment by DomHeinzeller** [comment]
fv3atm was just updated (PR https://github.com/NOAA-GSD/fv3atm/pull/27; submodule pointer update only). Please update your branch. Thanks!

**Comment by SamuelTrahanNOAA** [comment]
The aforementioned problems are resolved in my latest commit.

**Comment by DomHeinzeller** [comment]
I merged https://github.com/NOAA-GSD/ccpp-physics/pull/27. Can you please update the submodule pointer for ccpp-physics in your fv3atm branch to point to:
```
commit 238c84cb3c789056c701b70d3373e640ed4fa599 (HEAD, origin/gsd/develop, origin/HEAD)
Author: Samuel Trahan (NOAA contractor) <39415369+SamuelTrahanNOAA@users.noreply.github.com>
Date:   Wed May 13 22:20:32 2020 -0400

    fix bugs found in pbl and ozone 3d diagnostic tendencies (#27)

    PBL tendencies were missing in two schemes; now fixed. Squashed commit of:
    * fix bugs found in pbl and ozone 3d diagnostic tendencies
    * remove debugging prints
    * implied shape arrays for five variables
    * more block labels
    * yet more bug fixes
```
Then, fix the merge conflict for ufs-weather-model and update the submodule pointer for fv3atm. Once this is done, I can approve and merge fv3atm. Thanks!

**Review by DomHeinzeller — APPROVED** [review]

**Pull request merged**
