### PR TITLE
Move aerodp from GFS_interstitial_type to GFS_radtend_type

### PR DESCRIPTION
**Pull request by climbfuji**
# DRAFT

@hannahcbarnes please see this branch. You can simply pull this branch into the latest fv3atm gsl/develop branch.

Please let me know if this solves the problem you have been seeing with the aerodp variable.

## Description

(Instructions: this, and all subsequent sections of text should be removed and filled in as appropriate.)
Provide a detailed description of what this PR does.  
What bug does it fix, or what feature does it add?  
Is a change of answers expected from this PR?  

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #<issue_number>
- fixes noaa-emc/fv3atm/issues/<issue_number>

## Testing

How were these changes tested?  
What compilers / HPCs was it tested with?  
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Have the ufs-weather-model regression test been run? On what platform?  
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

### CODE REVIEW

**Comment by hannahcbarnes** [comment]
Thanks @climbfuji, this change did the trick. No more weird tile issue.

**Comment by climbfuji** [comment]
> Thanks @climbfuji, this change did the trick. No more weird tile issue.

Thanks for letting me know. Please include my changes when you submit changes that include aerodp in GF in the future.

**Comment by DomHeinzeller** [comment]
@hannahcbarnes Do you still need the changes in this PR? Will there be a ccpp-physics PR that uses them anytime soon?

**Comment by hannahcbarnes** [comment]
I have this incorporated to some of my codes I am currently testing. It will become a part of a PR, but not exactly sure when. You can remove this PR and I can include it in one of my future GF PRs.

**Comment by DomHeinzeller** [comment]
If there will be a need for a PR in the future, then I'll leave it as a draft PR for now. Thanks!

**Pull request closed without merging**
