### PR TITLE
GF_Tune_Oct2021

### PR DESCRIPTION
**Pull request by hannahcbarnes**
- Aerosol-awareness in GF is turned back on
- clwdet (cloud-water detrainment) is tuned
- evfact (evaporation fraction) and tun_rad_deep, tun_rad_mid (radiation factors) are made scale-aware

### CODE REVIEW

**Comment by DomHeinzeller** [comment]
Associated PRs:

https://github.com/NOAA-GSL/ccpp-physics/pull/108
https://github.com/NOAA-GSL/fv3atm/pull/110
https://github.com/NOAA-GSL/ufs-weather-model/pull/104

**Comment by DomHeinzeller** [comment]
For regression testing, see https://github.com/NOAA-GSL/ufs-weather-model/pull/104.

**Comment by DomHeinzeller** [comment]
@hannahcbarnes I merged your ccpp-physics PR. Please update the submodule pointer in your fv3atm PR to point back to the head of gsl/develop, the correct hash is dd94d8d.

**Comment by hannahcbarnes** [comment]
@DomHeinzeller Sure, how do I go about updating the submodule pointer?

**Comment by DomHeinzeller** [comment]
> @DomHeinzeller Sure, how do I go about updating the submodule pointer?

In your local code base (from which you created the PRs), go to ccpp-physics, make sure that you have noaa-gsl configured as one of the remotes (`git remote -v show`), then `git remote update`, then `git checkout NAME_OF_THE_NOAA_GSL_REMOTE/gsl/develop`.

Then go back to `FV3`, do `git status`. You should see that something has changed for `ccpp/physics` (new commits). `git add ccpp/physics`, `git commit -m "Update submodule pointer for ccpp-physics`, then push to github to your fv3atm branch.

**Comment by hannahcbarnes** [comment]
Let me know if that worked

**Comment by DomHeinzeller** [comment]
Nope. It's pointing back to the old gsl/develop hash (before the merge of your PR). Let me send you the changes.

**Comment by hannahcbarnes** [comment]
Would a git pull and git merge of the latest ccpp-physics fix it?

**Comment by climbfuji** [comment]
This is what I did:
```
cd FV3/ccpp/physics/
git remote update
git remote -v show
git checkout origin/gsl/develop
git log
cd ../..
git status
git add ccpp/physics
git commit -m "Update submodule pointer for ccpp/physics"
```

**Comment by climbfuji** [comment]
Just merge https://github.com/hannahcbarnes/fv3atm/pull/1 and we can merge your fv3atm PR.

**Comment by hannahcbarnes** [comment]
Thanks, I see that I did wrong. I missed the "origin" part in the git checkout.

**Review by DomHeinzeller — APPROVED** [review]

**Pull request merged**
