### PR TITLE
boundary condition bug fixes and RUC LSM precision fix

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
This fixes many bugs in regional boundary conditions, and a precision issue in module_sf_ruclsm. It is a copy of a community PR, with a different destination (RRFS_dev).

Community PR:

https://github.com/NOAA-EMC/fv3atm/pull/587

Dependencies:

https://github.com/NOAA-GSL/ccpp-physics/pull/163
https://github.com/NOAA-GSL/GFDL_atmos_cubed_sphere/pull/12

### CODE REVIEW

**Review by hannahcbarnes — APPROVED** [review]

**Review by haiqinli — APPROVED** [review]

**Comment by hu5970** [comment]
@SamuelTrahanNOAA Other than updates to the tests, this PR changed two files:
model/fv_regional_bc.F90
physics/module_sf_ruclsm.F90

Right?

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA Other than updates to the tests, this PR changed two files: model/fv_regional_bc.F90 physics/module_sf_ruclsm.F90
> 
> Right?

Correct.

**Comment by hu5970** [comment]
> > @SamuelTrahanNOAA Other than updates to the tests, this PR changed two files: model/fv_regional_bc.F90 physics/module_sf_ruclsm.F90
> > Right?
> 
> Correct.

Great, I will update this two files in my retro and run retro again. Thanks, Ming

**Review by hu5970 — APPROVED** [review]

**Comment by hu5970** [comment]
@SamuelTrahanNOAA Could you germ this PR and then let Haiqin update his PR? Thanks, Ming

**Comment by hu5970** [comment]
@haiqinli Please update your PR based on this one and finalize your PR as soon as possible. Thanks, Ming

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA Could you germ this PR and then let Haiqin update his PR? Thanks, Ming

I'm waiting for review from someone in the know before germing the PR. I've never even looked at fv_regional_bc.F90 until Monday, so I want someone who understands it to confirm I'm not just breaking things further.

**Comment by SamuelTrahanNOAA** [comment]
> @haiqinli Please update your PR based on this one and finalize your PR as soon as possible. Thanks, Ming

I have bug fixes to put on top of @haiqinli's changes. The sooner he finalizes those, the sooner I can apply my bug fixes.

He may be able to fix some of the issues himself if he applies these changes and runs in debug and 2threads modes.  Things crashed sometimes when I changed the thread count. I have fixes for that, and other problems.

_Edit: Ravan has reported threading-related crashes in other situations when he disables blocks of code. (Blocks that shouldn't cause crashes.) I'm hoping my threading-related bug fixes will correct that as well._

**Comment by haiqinli** [comment]
@hu5970 Yes, the updates of smoke code in my PR is done. I will include this boundary condition update into my PR and finalize it soon.

**Comment by SamuelTrahanNOAA** [comment]
@haiqinli Remember to include the module_sf_ruclsm fix too, otherwise the debug mode will fail due to a precision issue.

**Comment by haiqinli** [comment]
@SamuelTrahanNOAA Sure, I am doing a quick test run with my PR to include the  module_sf_ruclsm fix.

**Comment by SamuelTrahanNOAA** [comment]
@haiqinli If you can also compile with "-DDEBUG=ON" and get that to run with smoke, it'll save me a lot of time.

**Comment by haiqinli** [comment]
@SamuelTrahanNOAA Sure, I will compile with "-DDEBUG=ON".

**Comment by SamuelTrahanNOAA** [comment]
> @SamuelTrahanNOAA Sure, I will compile with "-DDEBUG=ON".

The fixes for debug, restart, and threading are in the bugfix/rrfs-debug-mode branch of my ccpp-physics fork. They're also necessary to get smoke to run without crashing on a restart. That is based on the community version of smoke, but most of the changes should be valid for the current version. You won't be able to test the threading properly since the RRFS_dev does not match its control in 2threads mode. We will have to trust to fate that the thread bugfixes will fix this newer smoke code too, as there is no other way to test it. However, we can test debug and restart.

https://github.com/SamuelTrahanNOAA/ccpp-physics/tree/bugfix/rrfs-debug-mode

git clone --branch bugfix/rrfs-debug-mode --recursive https://github.com/SamuelTrahanNOAA/ccpp-physics rrfs-debug-mode

**Review by zhanglikate — APPROVED** [review]

**Review by mdtoyNOAA — APPROVED** [review]

**Review by tanyasmirnova — APPROVED** [review]
@SamuelTrahanNOAA Ai approve the workaround in RUC LSM. Thank you, Sam, for discovering this problem. 
I am not familiar with the fv_regional_bc.F90 code, but the changes look reasonable to me, therefore, I approve these changes.

**Comment by haiqinli** [comment]
@hu5970 @SamuelTrahanNOAA  My PR is finalized with smoke, ruc_lsm, and regional_bc updates, and works well in debug mode.

**Comment by SamuelTrahanNOAA** [comment]
@haiqinli Where is the test case that you want me to turn into regression tests?

**Comment by hu5970** [comment]
@SamuelTrahanNOAA @haiqinli The latest CONUS 13km case should be used for smoe/dust regression test by turning option on, right?

**Comment by haiqinli** [comment]
@hu5970  If there is only one CONUS13km regression test run case, I suggest turning on smoke/dust option.

**Comment by SamuelTrahanNOAA** [comment]
All three will be present (no smoke, smoke, radar_tten)

**Pull request merged**
