### PR TITLE
Update of subgrid-scale cloud physics for MYNN/GF

### PR DESCRIPTION
**Pull request by climbfuji**
This PR updates the suite definition files with the new name of the subgrid-scale cloud scheme for MYNN/GF (changed from `mynnrad_{pre,post}` to `sgscloudrad_{pre,post}`) and adds a new variable `qci_conv` for GSDCHEM to `GFS_typedefs.{F90,meta}`.

Associated PRs:
https://github.com/NOAA-GSD/ccpp-physics/pull/2
https://github.com/NOAA-GSD/fv3atm/pull/3
https://github.com/NOAA-GSD/ufs-weather-model/pull/2

For regression testing, see below.

### CODE REVIEW

**Comment by DomHeinzeller** [comment]
@haiqinli @joeolson42 @tanyasmirnova please review this PR and post your comment here (I cannot add you as official reviewers). Thanks.

**Review by haiqinli — APPROVED** [review]
It looks good to me. Thanks.

**Comment by tanyasmirnova** [comment]
Dom,
My comment is on NOAA-GSD/ccpp-physics#2 PR.
I can't approve until I hear from Haiqin and Joe.
Thanks,
Tanya

**Comment by climbfuji** [comment]
Testing on macOS: The code as of Dec 13, 2019 5pm MT gives b4b identical results between IPD, CCPP dynamic and CCPP static for the fv3_gfdlmp/fv3_ccpp_gfdlmp regression tests with 32bit dynamics. The code also gives b4b identical results for CCP dynamic and CCPP static for the fv3_ccpp_gsd regression test with 64bit dynamics.

**Comment by climbfuji** [comment]
Regression testing on hera/intel against official EMC baseline (trunk-20191121): the following tests did not pass, all others pass. This is OK, because these tests have been changed/added by DTC and merged into gsd/develop, but not yet into EMC's code.
```
rt_55_fv3_gfdlmprad_repro
rt_81_fv3_ccpp_gfdlmprad_repro
rt_101_fv3_ccpp_gsd_repro
rt_113_fv3_ccpp_gfdlmprad_prod
rt_114_fv3_ccpp_wrtGauss_nemsio_c768_prod
rt_135_fv3_ccpp_gsd_prod
```

**Review by DomHeinzeller — CHANGES_REQUESTED** [review]
This PR cannot be merged, the fv3_ccpp_gsd_warmstart regression tests (part of rt_ccpp_gsd.conf) fail:

On hera/intel, using rt_ccpp_gsd.conf (first create, then verify): fv3_ccpp_gsd_warmstart fails.

[rt_ccpp_gsd_create.log](https://github.com/NOAA-GSD/fv3atm/files/3965004/rt_ccpp_gsd_create.log)
[rt_ccpp_gsd_verify.log](https://github.com/NOAA-GSD/fv3atm/files/3965005/rt_ccpp_gsd_verify.log)

**Comment by DomHeinzeller** [comment]
Regression testing on hera/intel using rt_ccpp_dtc.conf (first create, then verify): all pass.

[rt_ccpp_dtc_create.log](https://github.com/NOAA-GSD/fv3atm/files/3964997/rt_ccpp_dtc_create.log)
[rt_ccpp_dtc_verify.log](https://github.com/NOAA-GSD/fv3atm/files/3964998/rt_ccpp_dtc_verify.log)

**Review by DomHeinzeller — APPROVED** [review]

**Review by haiqinli — APPROVED** [review]

**Comment by DomHeinzeller** [comment]
@haiqinli @tanyasmirnova @joeolson42 @hannahcbarnes I believe this PR has been superseded by #13 which I just merged? Please confirm. Thanks!

**Comment by climbfuji** [comment]
Superseded by https://github.com/NOAA-GSD/fv3atm/pull/13.

**Pull request closed without merging**
