### PR TITLE
Fix the bug for diag. emission and add rain_cplchm and snow_cplchm 

### PR DESCRIPTION
**Pull request by zhanglikate**
Fix the bug for diag. emission and add rain_cplchm and snow_cplchm for chemical model, and will not share the rain_cpl and
 snow_cpl with Ocean model.
## Description

(Instructions: this, and all subsequent sections of text should be removed and filled in as appropriate.)
Provide a detailed description of what this PR does.  
What bug does it fix, or what feature does it add?  
Is a change of answers expected from this PR?  

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #<issue_number>
- fixes noaa-emc/fv3atm/issues/<issue_number>

## Testing

How were these changes tested?  
What compilers / HPCs was it tested with?  
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Have the ufs-weather-model regression test been run? On what platform?  
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
I'll run the regression tests on Hera to make sure they pass before we merge this.

Do you expect the results of the regression tests to change?

**Comment by SamuelTrahanNOAA** [comment]
The ccpp-physics PR is here:

https://github.com/NOAA-GSL/ccpp-physics/pull/95

There is no ufs-weather-model PR for this yet.

**Comment by zhanglikate** [comment]
Hi Sam,

       Thanks very much. There will be no change for the regression test
results. Thanks.

Li

**Comment by SamuelTrahanNOAA** [comment]
Regression tests passed:

Intel = /scratch2/BMC/wrfruc/Samuel.Trahan/perturb-smoke/intel-li-diag-change/tests/RegressionTests_hera.intel.log
GNU = /scratch2/BMC/wrfruc/Samuel.Trahan/perturb-smoke/gnu-li-diag-change/tests/RegressionTests_hera.gnu.log

**Review by haiqinli — APPROVED** [review]

**Comment by SamuelTrahanNOAA** [comment]
PR has been manually merged.

**Comment by climbfuji** [comment]
Thanks for taking care of this @SamuelTrahanNOAA .

**Pull request closed without merging**
